In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn.metrics import f1_score
from sklearn.svm import SVR
from keras.models import Sequential
from keras.layers import Dense
import seaborn as sns
from sklearn.metrics import accuracy_score

In [2]:
train_set = pd.read_excel("train_data.xlsx")
print(train_set.head())

   uid  key1_hold_dur  key2_hold_dur  DD_dur  UU_dur  UD_dur
0    1             96             88      96      88       0
1    1            176            112      64       0    -112
2    1            136            104      32       0    -104
3    1            113             73      40       0     -73
4    1             96             88      96      88       0


In [3]:
test_set = pd.read_excel("test_data.xlsx")
print(test_set.head())

   uid  key1_hold_dur  key2_hold_dur  DD_dur  UU_dur  UD_dur
0    1            120             76     164     120      44
1    1             80             64      80      64       0
2    1             80             63      81      64       1
3    1            104            109      84      89     -20
4    1             80             96     104     120      24


In [4]:
X_train = train_set.drop('uid', axis=1)
X_test = test_set.drop('uid', axis=1)
y_train = train_set['uid']
y_test = test_set['uid']

In [5]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
rfc = RandomForestClassifier(n_estimators=1000)
rfc.fit(X_train, y_train)
pred_rfc = rfc.predict(X_test)

In [7]:
print(classification_report(y_test, pred_rfc))
print(confusion_matrix(y_test, pred_rfc))

              precision    recall  f1-score   support

           0       0.82      0.59      0.68        46
           1       0.47      0.74      0.58        23

    accuracy                           0.64        69
   macro avg       0.65      0.66      0.63        69
weighted avg       0.70      0.64      0.65        69

[[27 19]
 [ 6 17]]


In [8]:
clf = svm.SVC()
clf.fit(X_train, y_train)
pred_clf = clf.predict(X_test)

In [9]:
print(classification_report(y_test, pred_clf))
print(confusion_matrix(y_test, pred_clf))

              precision    recall  f1-score   support

           0       0.72      0.93      0.81        46
           1       0.67      0.26      0.38        23

    accuracy                           0.71        69
   macro avg       0.69      0.60      0.59        69
weighted avg       0.70      0.71      0.67        69

[[43  3]
 [17  6]]


In [10]:
mlpc=MLPClassifier(hidden_layer_sizes=(20,20,20,20),max_iter=2000)
mlpc.fit(X_train, y_train)
pred_mlpc = mlpc.predict(X_test)
print(classification_report(y_test, pred_mlpc))
print(confusion_matrix(y_test, pred_mlpc))

              precision    recall  f1-score   support

           0       0.72      0.74      0.73        46
           1       0.45      0.43      0.44        23

    accuracy                           0.64        69
   macro avg       0.59      0.59      0.59        69
weighted avg       0.63      0.64      0.64        69

[[34 12]
 [13 10]]


In [11]:
attack_set = pd.read_excel("attack_data.xlsx")
print(attack_set.head())

   uid  key1_hold_dur  key2_hold_dur  DD_dur  UU_dur  UD_dur
0    1             80            120      96     136      16
1    1            112             80     104      72      -8
2    1             64            101      91     128      27
3    1            112             63     112      63       0
4    1             80             88      80      88       0


In [12]:
X1 = attack_set.drop('uid', axis=1)
y2 = attack_set['uid']
X1 = sc.transform(X1)
pred_rfc2 = rfc.predict(X1)
print(classification_report(y2, pred_rfc2))
print(confusion_matrix(y2, pred_rfc2))

              precision    recall  f1-score   support

           0       0.79      0.65      0.71        46
           1       0.47      0.64      0.54        22

    accuracy                           0.65        68
   macro avg       0.63      0.64      0.63        68
weighted avg       0.69      0.65      0.66        68

[[30 16]
 [ 8 14]]


In [13]:
pred_clf2 = clf.predict(X1)
print(classification_report(y2, pred_clf2))
print(confusion_matrix(y2, pred_clf2))

              precision    recall  f1-score   support

           0       0.69      0.93      0.80        46
           1       0.50      0.14      0.21        22

    accuracy                           0.68        68
   macro avg       0.60      0.54      0.51        68
weighted avg       0.63      0.68      0.61        68

[[43  3]
 [19  3]]


In [14]:
pred_mlpc2 = mlpc.predict(X1)
print(classification_report(y2, pred_mlpc2))
print(confusion_matrix(y2, pred_mlpc2))

              precision    recall  f1-score   support

           0       0.75      0.72      0.73        46
           1       0.46      0.50      0.48        22

    accuracy                           0.65        68
   macro avg       0.60      0.61      0.61        68
weighted avg       0.66      0.65      0.65        68

[[33 13]
 [11 11]]
