In [2]:
import os
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neural_network import MLPClassifier
from sklearn import svm
from sklearn.metrics import f1_score
from sklearn.svm import SVR
from keras.models import Sequential
from keras.layers import Dense
import seaborn as sns
from sklearn.metrics import accuracy_score

Random Forest Classifier Model Training and Attack

In [51]:
def rfc_model(X_train,X_test,y_train,y_test,X1,y2):
    rfc = RandomForestClassifier(n_estimators=1000)
    rfc.fit(X_train, y_train)
    pred_rfc = rfc.predict(X_test)
    print("\n RFC:")
    print(classification_report(y_test, pred_rfc))
    print(confusion_matrix(y_test, pred_rfc))
    print("\n RFC Attack:")
    pred_rfc2 = rfc.predict(X1)
    print(classification_report(y2, pred_rfc2))
    print(confusion_matrix(y2, pred_rfc2))

SVM Model Training and Attack

In [52]:
def svm_model(X_train,X_test,y_train,y_test,X1,y2):
    clf = svm.SVC()
    clf.fit(X_train, y_train)
    pred_clf = clf.predict(X_test)
    print("\n SVM:")
    print(classification_report(y_test, pred_clf))
    print(confusion_matrix(y_test, pred_clf))
    print("\n SVM Attack:")
    pred_clf2 = clf.predict(X1)
    print(classification_report(y2, pred_clf2))
    print(confusion_matrix(y2, pred_clf2))

Neural Net Model Training and Attack

In [57]:
def mlpc_model(X_train,X_test,y_train,y_test,X1,y2):
    mlpc=MLPClassifier(hidden_layer_sizes=(20,20,20,20),max_iter=2000)
    mlpc.fit(X_train, y_train)
    pred_mlpc = mlpc.predict(X_test)
    print("\n mlpc:")
    print(classification_report(y_test, pred_mlpc))
    print(confusion_matrix(y_test, pred_mlpc))
    print("\n MLPC Attack:")
    pred_mlpc2 = mlpc.predict(X1)
    print(classification_report(y2, pred_mlpc2))
    print(confusion_matrix(y2, pred_mlpc2))

Taking CSV data for Training, Testing and Attacking and feeding it into the Model Methods

In [58]:
def data_split(train_test_file,attack_file):
    train_csv = train_test_file[0]
    test_csv = train_test_file[1]
    
    train_set = pd.read_csv("train_test_attack_v2/TrainTest/"+str(train_csv))
    test_set = pd.read_csv("train_test_attack_v2/TrainTest/"+str(test_csv))
    attack_set = pd.read_csv("train_test_attack_v2/Attack/"+str(attack_file))
    
    X_train = train_set.drop('uid', axis=1)
    X_test = test_set.drop('uid', axis=1)
    y_train = train_set['uid']
    y_test = test_set['uid']
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    X1 = attack_set.drop('uid', axis=1)
    y2 = attack_set['uid']
    X1 = sc.transform(X1)
    
    rfc_model(X_train,X_test,y_train,y_test,X1,y2)
    svm_model(X_train,X_test,y_train,y_test,X1,y2)
    mlpc_model(X_train,X_test,y_train,y_test,X1,y2)


Reading the Data From the Directories

In [59]:
files = os.listdir("train_test_attack_v2/TrainTest")
tuples = []
for num in range(1,31):
    sub_a = "a"+str(num)+"-"
    sub_b = "b"+str(num)+"-"
    file_a = ""
    file_b = ""
    for file in files:
        if sub_a in file:
            file_a = file
        if sub_b in file:
            file_b = file
    new_tuple = file_a,file_b
    tuples.append(new_tuple)

attack_files = os.listdir("train_test_attack_v2/Attack")
sorted_attack_files = []
for num in range(1,31):
    sub_a = "Attack"+str(num)+"with"
    file_a = ""
    for file in attack_files:
        if sub_a in file:
            sorted_attack_files.append(file)

Running the Model and Displaying the Results

In [60]:
classification_models = []

for num in range(0,30):
    print(str(tuples[num])+"\n"+str(sorted_attack_files[num]))
    data_split(tuples[num], sorted_attack_files[num])
    

('a1-2-4.csv', 'b1-14-18.csv')
Attack1with20-4-24.csv

 RFC:
              precision    recall  f1-score   support

           0       0.85      0.37      0.52        46
           1       0.41      0.87      0.56        23

    accuracy                           0.54        69
   macro avg       0.63      0.62      0.54        69
weighted avg       0.70      0.54      0.53        69

[[17 29]
 [ 3 20]]

 RFC Attack:
              precision    recall  f1-score   support

           0       1.00      0.65      0.79        52
           1       0.59      1.00      0.74        26

    accuracy                           0.77        78
   macro avg       0.80      0.83      0.77        78
weighted avg       0.86      0.77      0.77        78

[[34 18]
 [ 0 26]]

 SVM:
              precision    recall  f1-score   support

           0       0.85      0.37      0.52        46
           1       0.41      0.87      0.56        23

    accuracy                           0.54        69
   macro


 RFC:
              precision    recall  f1-score   support

           0       0.82      1.00      0.90        14
           1       1.00      0.57      0.73         7

    accuracy                           0.86        21
   macro avg       0.91      0.79      0.82        21
weighted avg       0.88      0.86      0.84        21

[[14  0]
 [ 3  4]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.93      0.98      0.95        42
           1       0.95      0.86      0.90        21

    accuracy                           0.94        63
   macro avg       0.94      0.92      0.93        63
weighted avg       0.94      0.94      0.94        63

[[41  1]
 [ 3 18]]

 SVM:
              precision    recall  f1-score   support

           0       0.81      0.93      0.87        14
           1       0.80      0.57      0.67         7

    accuracy                           0.81        21
   macro avg       0.81      0.75      0.77        21
weighted


 RFC:
              precision    recall  f1-score   support

           0       0.82      0.45      0.58        20
           1       0.45      0.82      0.58        11

    accuracy                           0.58        31
   macro avg       0.63      0.63      0.58        31
weighted avg       0.69      0.58      0.58        31

[[ 9 11]
 [ 2  9]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.88      0.50      0.64        42
           1       0.46      0.86      0.60        21

    accuracy                           0.62        63
   macro avg       0.67      0.68      0.62        63
weighted avg       0.74      0.62      0.62        63

[[21 21]
 [ 3 18]]

 SVM:
              precision    recall  f1-score   support

           0       0.83      1.00      0.91        20
           1       1.00      0.64      0.78        11

    accuracy                           0.87        31
   macro avg       0.92      0.82      0.84        31
weighted


 RFC:
              precision    recall  f1-score   support

           0       0.71      0.16      0.26        32
           1       0.34      0.88      0.49        16

    accuracy                           0.40        48
   macro avg       0.53      0.52      0.37        48
weighted avg       0.59      0.40      0.33        48

[[ 5 27]
 [ 2 14]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.94      0.69      0.79        64
           1       0.59      0.91      0.72        32

    accuracy                           0.76        96
   macro avg       0.76      0.80      0.75        96
weighted avg       0.82      0.76      0.77        96

[[44 20]
 [ 3 29]]

 SVM:
              precision    recall  f1-score   support

           0       0.60      0.09      0.16        32
           1       0.33      0.88      0.47        16

    accuracy                           0.35        48
   macro avg       0.46      0.48      0.32        48
weighted

C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



 RFC:
              precision    recall  f1-score   support

           0       0.87      0.81      0.84        16
           1       0.67      0.75      0.71         8

    accuracy                           0.79        24
   macro avg       0.77      0.78      0.77        24
weighted avg       0.80      0.79      0.79        24

[[13  3]
 [ 2  6]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.82      0.65      0.72        62
           1       0.50      0.71      0.59        31

    accuracy                           0.67        93
   macro avg       0.66      0.68      0.65        93
weighted avg       0.71      0.67      0.68        93

[[40 22]
 [ 9 22]]

 SVM:
              precision    recall  f1-score   support

           0       0.64      0.88      0.74        16
           1       0.00      0.00      0.00         8

    accuracy                           0.58        24
   macro avg       0.32      0.44      0.37        24
weighted


 RFC:
              precision    recall  f1-score   support

           0       0.67      0.43      0.52        14
           1       0.33      0.57      0.42         7

    accuracy                           0.48        21
   macro avg       0.50      0.50      0.47        21
weighted avg       0.56      0.48      0.49        21

[[6 8]
 [3 4]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.82      0.84      0.83        58
           1       0.67      0.62      0.64        29

    accuracy                           0.77        87
   macro avg       0.74      0.73      0.74        87
weighted avg       0.77      0.77      0.77        87

[[49  9]
 [11 18]]

 SVM:
              precision    recall  f1-score   support

           0       0.69      0.64      0.67        14
           1       0.38      0.43      0.40         7

    accuracy                           0.57        21
   macro avg       0.53      0.54      0.53        21
weighted avg


 RFC:
              precision    recall  f1-score   support

           0       0.77      0.36      0.49        28
           1       0.40      0.80      0.53        15

    accuracy                           0.51        43
   macro avg       0.58      0.58      0.51        43
weighted avg       0.64      0.51      0.50        43

[[10 18]
 [ 3 12]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.88      0.29      0.43        52
           1       0.39      0.92      0.55        26

    accuracy                           0.50        78
   macro avg       0.64      0.61      0.49        78
weighted avg       0.72      0.50      0.47        78

[[15 37]
 [ 2 24]]

 SVM:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84        28
           1       0.71      0.67      0.69        15

    accuracy                           0.79        43
   macro avg       0.77      0.76      0.77        43
weighted

C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tayzoon\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tayzoon\Anaconda3\lib\site-packages\skle


 RFC:
              precision    recall  f1-score   support

           0       0.62      0.12      0.21        40
           1       0.34      0.86      0.49        21

    accuracy                           0.38        61
   macro avg       0.48      0.49      0.35        61
weighted avg       0.53      0.38      0.30        61

[[ 5 35]
 [ 3 18]]

 RFC Attack:
              precision    recall  f1-score   support

           0       0.94      0.27      0.42        62
           1       0.40      0.97      0.57        31

    accuracy                           0.51        93
   macro avg       0.67      0.62      0.50        93
weighted avg       0.76      0.51      0.47        93

[[17 45]
 [ 1 30]]

 SVM:
              precision    recall  f1-score   support

           0       0.86      0.15      0.26        40
           1       0.37      0.95      0.53        21

    accuracy                           0.43        61
   macro avg       0.61      0.55      0.39        61
weighted


 RFC:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        10

    accuracy                           1.00        28
   macro avg       1.00      1.00      1.00        28
weighted avg       1.00      1.00      1.00        28

[[18  0]
 [ 0 10]]

 RFC Attack:
              precision    recall  f1-score   support

           0       1.00      0.50      0.67        16
           1       0.50      1.00      0.67         8

    accuracy                           0.67        24
   macro avg       0.75      0.75      0.67        24
weighted avg       0.83      0.67      0.67        24

[[8 8]
 [0 8]]

 SVM:
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        18
           1       1.00      0.90      0.95        10

    accuracy                           0.96        28
   macro avg       0.97      0.95      0.96        28
weighted avg